version: "3.9"
services:
  enthub-app:
    # platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   NEXT_PUBLIC_CLIENTVAR: "clientvar"
    env_file:
      - .env
    working_dir: /app
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    # tty: true
    environment:
      - WATCHPACK_POLLING=true
    # stdin_open: true
volumes:
  node_modules:
