name: Check ERD.md update

on:
  push:
    paths:
      - "prisma/**.prisma"

jobs:
  check-erd-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Prisma CLI
        run: npm install prisma prisma-erd-generator @mermaid-js/mermaid-cli

      - name: Generate ERD
        run: npx prisma generate

      - name: Check if ERD.md is up-to-date
        run: |
          git diff --exit-code prisma/ERD.md
        id: diff-check

      - name: Check if ERD.md is committed if there are changes
        if: steps.diff-check.outcome == 'failure'
        run: |
          if [[ $(git diff --name-only --cached | grep prisma/ERD.md) ]]; then
            echo "ERD.md has been committed."
          else
            echo "ERD.md has changes but is not committed. Please commit the updated ERD.md."
            exit 1
          fi
